// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: test.proto

package smartpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level int32

const (
	Level_Easy   Level = 0
	Level_Middle Level = 1
	Level_Hard   Level = 2
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "Easy",
		1: "Middle",
		2: "Hard",
	}
	Level_value = map[string]int32{
		"Easy":   0,
		"Middle": 1,
		"Hard":   2,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type Api1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	V3    *Api3  `protobuf:"bytes,3,opt,name=v3,proto3" json:"v3,omitempty"`
	Lv    Level  `protobuf:"varint,4,opt,name=lv,proto3,enum=protojson.Level" json:"lv,omitempty"`
}

func (x *Api1) Reset() {
	*x = Api1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Api1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api1) ProtoMessage() {}

func (x *Api1) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api1.ProtoReflect.Descriptor instead.
func (*Api1) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *Api1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Api1) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Api1) GetV3() *Api3 {
	if x != nil {
		return x.V3
	}
	return nil
}

func (x *Api1) GetLv() Level {
	if x != nil {
		return x.Lv
	}
	return Level_Easy
}

type Api2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Info *Api1   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Lvs  []Level `protobuf:"varint,3,rep,packed,name=lvs,proto3,enum=protojson.Level" json:"lvs,omitempty"`
}

func (x *Api2) Reset() {
	*x = Api2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Api2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api2) ProtoMessage() {}

func (x *Api2) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api2.ProtoReflect.Descriptor instead.
func (*Api2) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *Api2) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Api2) GetInfo() *Api1 {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Api2) GetLvs() []Level {
	if x != nil {
		return x.Lvs
	}
	return nil
}

type Api3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Likes []string `protobuf:"bytes,2,rep,name=likes,proto3" json:"likes,omitempty"`
	Times int32    `protobuf:"varint,3,opt,name=times,proto3" json:"times,omitempty"`
	V2    *Api2    `protobuf:"bytes,4,opt,name=v2,proto3" json:"v2,omitempty"`
}

func (x *Api3) Reset() {
	*x = Api3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Api3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api3) ProtoMessage() {}

func (x *Api3) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api3.ProtoReflect.Descriptor instead.
func (*Api3) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *Api3) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Api3) GetLikes() []string {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *Api3) GetTimes() int32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *Api3) GetV2() *Api2 {
	if x != nil {
		return x.V2
	}
	return nil
}

type Api4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*Api2   `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Admin *Api4Api6 `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *Api4) Reset() {
	*x = Api4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Api4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api4) ProtoMessage() {}

func (x *Api4) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api4.ProtoReflect.Descriptor instead.
func (*Api4) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *Api4) GetUsers() []*Api2 {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Api4) GetAdmin() *Api4Api6 {
	if x != nil {
		return x.Admin
	}
	return nil
}

type Api5 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V3 []*Api3 `protobuf:"bytes,1,rep,name=v3,proto3" json:"v3,omitempty"` // 对象数组
	V4 []*Api4 `protobuf:"bytes,2,rep,name=v4,proto3" json:"v4,omitempty"` // 对象数组的数组
}

func (x *Api5) Reset() {
	*x = Api5{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Api5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api5) ProtoMessage() {}

func (x *Api5) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api5.ProtoReflect.Descriptor instead.
func (*Api5) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *Api5) GetV3() []*Api3 {
	if x != nil {
		return x.V3
	}
	return nil
}

func (x *Api5) GetV4() []*Api4 {
	if x != nil {
		return x.V4
	}
	return nil
}

type Api4Api6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V2 *Api2 `protobuf:"bytes,1,opt,name=v2,proto3" json:"v2,omitempty"`
}

func (x *Api4Api6) Reset() {
	*x = Api4Api6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Api4Api6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api4Api6) ProtoMessage() {}

func (x *Api4Api6) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api4Api6.ProtoReflect.Descriptor instead.
func (*Api4Api6) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Api4Api6) GetV2() *Api2 {
	if x != nil {
		return x.V2
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x73, 0x0a, 0x04, 0x61, 0x70, 0x69, 0x31, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x02, 0x76, 0x33, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73, 0x6f,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x33, 0x52, 0x02, 0x76, 0x33, 0x12, 0x20, 0x0a, 0x02, 0x6c, 0x76,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73,
	0x6f, 0x6e, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x02, 0x6c, 0x76, 0x22, 0x5f, 0x0a, 0x04,
	0x61, 0x70, 0x69, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x31, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x03, 0x6c, 0x76, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73,
	0x6f, 0x6e, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x03, 0x6c, 0x76, 0x73, 0x22, 0x67, 0x0a,
	0x04, 0x61, 0x70, 0x69, 0x33, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x02, 0x76, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x32, 0x52, 0x02, 0x76, 0x32, 0x22, 0x82, 0x01, 0x0a, 0x04, 0x61, 0x70, 0x69, 0x34, 0x12,
	0x25, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x32, 0x52,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73, 0x6f,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x34, 0x2e, 0x61, 0x70, 0x69, 0x36, 0x52, 0x05, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x1a, 0x27, 0x0a, 0x04, 0x61, 0x70, 0x69, 0x36, 0x12, 0x1f, 0x0a, 0x02, 0x76, 0x32,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73,
	0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x32, 0x52, 0x02, 0x76, 0x32, 0x22, 0x48, 0x0a, 0x04, 0x61,
	0x70, 0x69, 0x35, 0x12, 0x1f, 0x0a, 0x02, 0x76, 0x33, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x33,
	0x52, 0x02, 0x76, 0x33, 0x12, 0x1f, 0x0a, 0x02, 0x76, 0x34, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x34, 0x52, 0x02, 0x76, 0x34, 0x2a, 0x27, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x08,
	0x0a, 0x04, 0x45, 0x61, 0x73, 0x79, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x61, 0x72, 0x64, 0x10, 0x02, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_test_proto_goTypes = []interface{}{
	(Level)(0),       // 0: protojson.Level
	(*Api1)(nil),     // 1: protojson.api1
	(*Api2)(nil),     // 2: protojson.api2
	(*Api3)(nil),     // 3: protojson.api3
	(*Api4)(nil),     // 4: protojson.api4
	(*Api5)(nil),     // 5: protojson.api5
	(*Api4Api6)(nil), // 6: protojson.api4.api6
}
var file_test_proto_depIdxs = []int32{
	3,  // 0: protojson.api1.v3:type_name -> protojson.api3
	0,  // 1: protojson.api1.lv:type_name -> protojson.Level
	1,  // 2: protojson.api2.info:type_name -> protojson.api1
	0,  // 3: protojson.api2.lvs:type_name -> protojson.Level
	2,  // 4: protojson.api3.v2:type_name -> protojson.api2
	2,  // 5: protojson.api4.users:type_name -> protojson.api2
	6,  // 6: protojson.api4.admin:type_name -> protojson.api4.api6
	3,  // 7: protojson.api5.v3:type_name -> protojson.api3
	4,  // 8: protojson.api5.v4:type_name -> protojson.api4
	2,  // 9: protojson.api4.api6.v2:type_name -> protojson.api2
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Api1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Api2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Api3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Api4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Api5); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Api4Api6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
